-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local lspconfig = require('lspconfig')
-- lspconfig.vtsls.setup({
--   root_dir = function()
--     return vim.fn.getcwd()
--   end
-- })
--
--
